version: "3.8"


services:
  flask:
    container_name: web_resource_watchdog_app
    image: mikhailkas/web_resource_watchdog:latest
    entrypoint: /app/infra/flask-entrypoint.sh
    restart: always
    env_file:
      - ../.env
    ports:
      - "8000:${GUNICORN_PORT}"

    depends_on:
      - db

  db:
    container_name: postgres_database
    image: postgres:14.7-alpine
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:alpine

  celery:
    container_name: celery_workers
    image: mikhailkas/web_resource_watchdog:latest
    entrypoint: /app/infra/worker-entrypoint.sh
    restart: always
    env_file:
      - ../.env
    depends_on:
      - flask
      - redis
      - db

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    env_file:
      - ../.env
    ports:
      - "80:${NGINX_PORT}"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template

    depends_on:
      - flask
    restart: always

volumes:
  postgres_data:
