version: "3.8"


services:
  flask:
    image: mikhailkas/web_resource_watchdog:latest
    entrypoint: /app/infra/start_app.sh
    env_file:
      - ../.env
    ports:
      - "8000:${GUNICORN_PORT}"

    depends_on:
      - db


  db:
    image: postgres:14.7-alpine
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  nginx:
    image: nginx:1.21.3-alpine
    env_file:
      - ../.env
    ports:
      - "80:${NGINX_PORT}"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template

    depends_on:
      - flask
    restart: always

volumes:
  postgres_data:
