"""empty message

Revision ID: b7d7664b11f2
Revises:
Create Date: 2023-09-02 16:18:02.750588

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7d7664b11f2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "web_resource",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_url", sa.String(), nullable=False),
        sa.Column("protocol", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("domain_zone", sa.String(), nullable=False),
        sa.Column("url_path", sa.String(), nullable=True),
        sa.Column("query_params", sa.String(), nullable=True),
        sa.Column("screenshot", sa.LargeBinary(), nullable=True),
        sa.Column("fail_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_url"),
    )
    op.create_table(
        "web_resource_status",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column(
            "request_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("is_watched", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["web_resource.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("web_resource_status")
    op.drop_table("web_resource")
    # ### end Alembic commands ###
